"""Cold Memory — Append-only immutable ledger for Solar Swarm.

Every significant decision, experiment event, and circuit breaker
trigger is written here. Records are NEVER updated or deleted.
"""

import logging
from datetime import datetime
from memory.database import insert, fetch_all, json_payload

logger = logging.getLogger(__name__)


def log_event(
    event_type: str,
    event_data: dict,
    experiment_id: int = None,
    agent_id: str = None,
    human_involved: bool = False,
) -> int:
    """Append an immutable event record to the cold ledger.

    Args:
        event_type: Category of event (e.g. EXPERIMENT_CREATED, CIRCUIT_BREAKER_RED)
        event_data: Dict of relevant data for this event
        experiment_id: Associated experiment if applicable
        agent_id: Which agent triggered this event
        human_involved: True if a human approved/rejected

    Returns:
        The new ledger record id
    """
    row_id = insert("cold_ledger", {
        "event_type": event_type,
        "event_data": json_payload(event_data),
        "experiment_id": experiment_id,
        "agent_id": agent_id,
        "human_involved": 1 if human_involved else 0,
    })
    logger.info(f"[LEDGER] {event_type} | exp={experiment_id} | agent={agent_id}")
    return row_id


def log_experiment_created(experiment_id: int, idea_text: str, confidence: float, agent_id: str):
    """Log when a new experiment is generated by the General."""
    return log_event(
        "EXPERIMENT_CREATED",
        {"idea_text": idea_text, "confidence_score": confidence},
        experiment_id=experiment_id,
        agent_id=agent_id,
    )


def log_experiment_approved(experiment_id: int, approved_by: str, budget: float):
    """Log human or auto approval of an experiment."""
    return log_event(
        "EXPERIMENT_APPROVED",
        {"approved_by": approved_by, "budget_allocated": budget},
        experiment_id=experiment_id,
        agent_id="human_gate",
        human_involved=(approved_by != "auto"),
    )


def log_experiment_killed(experiment_id: int, reason: str, agent_id: str):
    """Log when an experiment is auto-killed or rejected."""
    return log_event(
        "EXPERIMENT_KILLED",
        {"reason": reason},
        experiment_id=experiment_id,
        agent_id=agent_id,
    )


def log_circuit_breaker(level: str, reason: str, data: dict):
    """Log a circuit breaker trigger."""
    return log_event(
        f"CIRCUIT_BREAKER_{level.upper()}",
        {"reason": reason, **data},
        agent_id="circuit_breaker",
    )


def log_lead_qualified(lead_id: int, score: float, action: str):
    """Log when a solar lead is scored."""
    return log_event(
        "LEAD_QUALIFIED",
        {"score": score, "action": action},
        agent_id="qualification_agent",
    )


def log_pheromone_signal(signal_type: str, topic: str, strength: float, experiment_id: int):
    """Log a pheromone signal posted by a worker."""
    return log_event(
        "PHEROMONE_SIGNAL",
        {"signal_type": signal_type, "topic": topic, "strength": strength},
        experiment_id=experiment_id,
        agent_id="worker",
    )


def get_recent_events(limit: int = 50) -> list:
    """Retrieve the most recent ledger entries."""
    return fetch_all(
        "SELECT * FROM cold_ledger ORDER BY created_at DESC LIMIT ?",
        (limit,),
    )


def get_events_by_type(event_type: str, limit: int = 100) -> list:
    """Retrieve ledger entries filtered by event type."""
    return fetch_all(
        "SELECT * FROM cold_ledger WHERE event_type = ? ORDER BY created_at DESC LIMIT ?",
        (event_type, limit),
    )
